name: sync-upstream
on:
  schedule:
    - cron: '23 * * * *'
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: GOG-Nebula/actions-sync-fork@main
        with:
          upstream_owner: UncleGoogle
          upstream_repo: galaxy-integration-humblebundle
          upstream_branch: master
          reviewers: urwrstkn8mare,AndrewDWhite
          token: ${{ secrets.GITHUB_TOKEN }}
